### ISSUE TITLE
Paper clip?

### ISSUE THREAD

**Issue by LornaLynch** [raspberrypilearning/robot-antenna#4]
In Step 3.8, the paper clip is mentioned as one of the parts which you put inside the cardboard tube. Can I confirm what the paper clip is doing? Clipping the wires onto the tube, holding the wires together, or something else? Sorry: couldn't visualise it, and it's the first time the clip has appeared.

**Comment by MissPhilbin** [comment]
I think we removed the paper clip from an earlier step and is now no longer required. Thanks for spotting this. Can you remove any mention of it please?

**Comment by LornaLynch** [comment]
Will do: I'll be able to do it this evening.

**Comment by bennuttall** [comment]
@LornaLynch did this get completed? Can we close the issue?

**Comment by LornaLynch** [comment]
Yes, all sorted.
