### ISSUE TITLE
Update to new Scratch

### ISSUE THREAD

**Issue by jrobinson-uk** [raspberrypilearning/robot-antenna#5]
- [ ] setup pin
- [ ] pin numbering (prose) 11 --> 17
- [ ] code block images
- [ ] wiring diagrams
- [ ] logging in steps & startx
- [ ] launching scratch (desktop icon)
- [ ] sound switch

**Comment by bennuttall** [comment]
@jrobinson-uk This was completed, right?

**Comment by MarcScott** [comment]
This looks done to me. Reopen if anyone has anything to add
